name: Deploy Hugo site to GitHub Pages

on:
  # Run workflow on pushes to the specified branches
  # push:
  #   branches:
  #     - main

  # Allow manual workflow trigger
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Clone the project and initialize submodules
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # Fetch Hugo themes (and other submodules)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      # Step 2: Build the Hugo project
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.148.1' # The Hugo version (https://github.com/gohugoio/hugo/releases)
          # extended: true # Uncomment if you need the extended version

      - name: Build
        run: hugo --minify # Builds the site and places it in the 'public' directory

      # Step 3: Upload the static site artifact
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
